name: Deploy Socket App to EC2

on:
  push:
    branches:
      - notusingnow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t socket-app .

      - name: Save Docker image
        run: docker save socket-app > socket-app.tar

      - name: Copy image to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "socket-app.tar"
          target: "/home/ec2-user/"

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker stop socket-app || true
            docker rm socket-app || true

            docker load < socket-app.tar

            docker run -d \
              --name socket-app \
              -p 8090:8090 \
              --env-file /home/ec2-user/.env \
              socket-app
